logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: DEBUG
server:
    port: 8000
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 1234
        url: jdbc:mysql://localhost:3306/mobilelele?createDatabaseIfNotExist=true
        username: root
    jpa:
        # Choose either MySQL 8 or MySQL 5 below
        # For MySQL 8
        database-platform: org.hibernate.dialect.MySQL8Dialect
        # For MySQL 5
        # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: create-drop
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
        defer-datasource-initialization: true
